### ISSUE TITLE
Asking for information

### ISSUE THREAD

**Issue by anakin87** [54rt1n/shardmerge#1]
**Hey, impressive work!**

I’m trying to understand Fourier Merging and would appreciate some pointers: papers, other resources, etc.

Practically speaking, instead, can you quickly explain this part of the configuration or point me to any relevant info?
```YML
output_base_model: "unsloth/Meta-Llama-3.1-70B-Instruct"
output_dtype: "bfloat16"
finetune_merge:
  - { "model": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF", "base": "unsloth/Meta-Llama-3.1-70B-Instruct", "alpha": 0.3, "is_input": true }
  - { "model": "another/finetuned-model", "base": "unsloth/Meta-Llama-3.1-70B-Instruct", "alpha": 0.5, "is_output": true }
  ...
  ```
